.before_script_template:
  before_script:
      - "python3 --version"
      - "pip install virtualenv -i https://pypi.tuna.tsinghua.edu.cn/simple"
      - "virtualenv venv"
      - "source venv/bin/activate"

cache:
  key: ${CI_JOB_NAME}
  paths:
    - .cache/pip
    - venv/


variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  
stages:
  - pages
  - tests

pages:
  extends: .before_script_template
  stage: pages
  image: python:latest
  script:
    - "pip install mkdocs mkdocs-autorefs mkdocs-material mkdocstrings[python] -i https://pypi.tuna.tsinghua.edu.cn/simple"
    - mkdocs build
  artifacts:
    paths:
      - public
  only:
    - dev

test_python3.8:
  extends: .before_script_template
  variables: 
    CIVREALM_HOST_URL: "http://freeciv_web"
    CIVREALM_TEST_SAVE_DIR: "/builds/civilization/civrealm/tests/game_save"
  stage: tests
  image: python:3.8
  services:
    - name: civrealm/freeciv-web:dev
      alias: freeciv_web
      command: 
        - '/bin/bash'
        - '-c'
        - |
          until [ -f "$CI_PROJECT_DIR/.git/index" ]; do true; done;
          while [ -f "$CI_PROJECT_DIR/.git/index.lock" ]; do true; done;
          python "$CI_PROJECT_DIR/copy_ci_test_saves.py";
          sleep infinity

  script:
    - "pip install -e . -i https://pypi.tuna.tsinghua.edu.cn/simple"
    - "sleep infinity"
  allow_failure: true

local_pytest:
  stage: tests
  script:
    - sudo pip install -e .
    - sudo rm /tmp/civrealm* && pytest -x
  tags:
    - local_pytest
