before_script:
  - "pip install mkdocs mkdocs-autorefs mkdocs-material mkdocstrings[python] -i https://pypi.tuna.tsinghua.edu.cn/simple"

stages:
  - pages

pages:
  stage: pages
  image: python:latest
  script:
    - mkdocs build
  artifacts:
    paths:
      - public
  only:
    - dev
