variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  CI_DEBUG_SERVICES: "FALSE"
  FREECIV_IMAGE_VERSION: civrealm/freeciv-web:dev

cache:
  key: "${CI_JOB_NAME}-${CI_COMMIT_REF_SLUG}"
  paths:
    - .cache/pip
    - venv/
    - minigame.zip

.before_script_template:
  before_script:
    - "python3 --version"
    - "pip install virtualenv -i https://pypi.tuna.tsinghua.edu.cn/simple"
    - "virtualenv venv"
    - "source venv/bin/activate"

.python_test_template: &python_test_template
  stage: tests
  services:
    - name: $FREECIV_IMAGE_VERSION
      alias: freeciv
      entrypoint:
        - "/bin/bash"
        - "-c"
        - |
          until [ -f "$CI_PROJECT_DIR/.git/index" ]; do true ; done;
          while [ -f "$CI_PROJECT_DIR/.git/index.lock" ]; do true ; done;
          python3 "$CI_PROJECT_DIR/copy_ci_test_saves.py"
          /docker/docker-entrypoint.sh && sleep infinity
  variables:
    CIVREALM_HOST_URL: "freeciv"
    CIVREALM_HOST_PORT: "80"
  script:
    - "pip install -e . -i https://pypi.tuna.tsinghua.edu.cn/simple"
    - until [ -f "minitask_zipped.flag" ]; do sleep 60 && echo "Waiting for minigame.zip to be downloaded!" ; done;
    - until curl --output /dev/null --silent --fail "$CIVREALM_HOST_URL:$CIVREALM_HOST_PORT/pubstatus"; do sleep 60 && echo "Waiting for freeciv-web server to set up!" ; done;
    - "pytest -vv -x"

stages:
  - pages
  - tests

pages:
  extends: .before_script_template
  stage: pages
  image: python:latest
  script:
    - "pip install mkdocs mkdocs-autorefs mkdocs-material mkdocstrings[python] -i https://pypi.tuna.tsinghua.edu.cn/simple"
    - mkdocs build
  artifacts:
    paths:
      - public
  only:
    - dev

test_python3.8:
  image: python:3.8
  extends:
    - .before_script_template
  allow_failure: true
  <<: *python_test_template

test_python3.9:
  image: python:3.9
  extends:
    - .before_script_template
  allow_failure: true
  <<: *python_test_template

test_python3.10:
  image: python:3.10
  extends:
    - .before_script_template
  allow_failure: true
  <<: *python_test_template

test_python3.11:
  image: python:3.11
  extends:
    - .before_script_template
  allow_failure: true
  <<: *python_test_template

local_pytest:
  stage: tests
  script:
    - sudo pip install -e .
    - pytest -x
  tags:
    - local_pytest

