.before_script_template:
  before_script:
    - "python3 --version"
    - "pip install virtualenv -i https://pypi.tuna.tsinghua.edu.cn/simple"
    - "virtualenv venv"
    - "source venv/bin/activate"

.python_test_template:
  stage: tests
  services:
    - name: civrealm/freeciv-web:dev
      alias: freeciv_web
      variables:
        CIVREALM_TEST_SAVE_DIR: "$CI_PROJECT_DIR/tests/game_save"
      command:
        - "/bin/bash"
        - "-c"
        - |
          until [ -f "$CI_PROJECT_DIR/.git/index" ]; do true; done;
          while [ -f "$CI_PROJECT_DIR/.git/index.lock" ]; do true; done;
          python "$CI_PROJECT_DIR/copy_ci_test_saves.py";
          sleep infinity
  variables:
    CIVREALM_HOST_URL: "freeciv_web"
    CIVREALM_HOST_PORT: "80"
  script:
    - "pip install -e . -i https://pypi.tuna.tsinghua.edu.cn/simple"
    - "touch pytest.ini"
  allow_failure: true

cache:
  key: "${CI_JOB_NAME}-${CI_COMMIT_REF_SLUG}"
  paths:
    - .cache/pip
    - venv/

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

stages:
  - tests
  - pages

pages:
  extends: .before_script_template
  stage: pages
  image: python:latest
  script:
    - "pip install mkdocs mkdocs-autorefs mkdocs-material mkdocstrings[python] -i https://pypi.tuna.tsinghua.edu.cn/simple"
    - mkdocs build
  artifacts:
    paths:
      - public
  only:
    - dev

test_python3.8:
  image: python:3.8
  extends:
    - .before_script_template
    - .python_test_template

local_pytest:
  stage: tests
  script:
    - sudo pip install -e .
    - pytest -x
  tags:
    - local_pytest
