# before_script:
#
stages:
  - pages
  - local_pytest
  - test

pages:
  stage: pages
  image: python:latest
  script:
    - "pip install mkdocs mkdocs-autorefs mkdocs-material mkdocstrings[python] -i https://pypi.tuna.tsinghua.edu.cn/simple"
    - mkdocs build
  artifacts:
    paths:
      - public
  only:
    - dev

test_python3.8:
  stage: test
  image: python:3.8
  services:
    - name: civrealm/freeciv-web:dev
      alias: freeciv_web
      command: ["sleep", "infinity"]
  script:
    - "pip install -e . -i https://pypi.tuna.tsinghua.edu.cn/simple"
    - "sed -i 's/host: localhost/host: freeciv_web/' default_settings.yaml"
    - "pytest -vv"

local_pytest:
  stage: local_pytest
  script:
    - pip install -e .
    - sudo rm /tmp/civrealm* && pytest -x
