before_script:
  - "pip install mkdocs mkdocs-autorefs mkdocs-material mkdocstrings[python] -i https://pypi.tuna.tsinghua.edu.cn/simple"

stages:
  - pages
  - pytest

pages:
  stage: pages
  image: python:latest
  script:
    - mkdocs build
  artifacts:
    paths:
      - public
  only:
    - dev

pytest:
  stage: pytest
  script:
    - mkdir repos && cd repos
    - git config --global url."https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.mybigai.ac.cn".insteadOf "ssh://git@gitlab.mybigai.ac.cn"
    - git clone ssh://git@gitlab.mybigai.ac.cn:2222/civilization/freeciv-tensor-baseline.git
    - cd freeciv-tensor-baseline && git pull && pip install -e .
    - cd ../.. && pip install -e .
    - python -m pytest -x

