gym_env: Freeciv-v0
out_dir: /tmp/random-agent-results

username: civbot
# Max number of turns per game
max_turns: 10
# The The port of the Freeciv server. The default is 6000. Should be 6001 if multiplayer_game is True.
client_port: 6001
# Whether to start in multiplayer mode or single player mode
multiplayer_game: True
# Whether to start hotseat game in single player mode
hotseat_game: False
# Whether to wait a observer join before start the game
wait_for_observer: False
# The seed used to generate a map
mapseed: 88
# Number of AI players
aifill: 0
# The maximum number of players
maxplayers: 10
# The minimum number of players that allows the game to start
minp: 1
# The allowtake setting decides whether can take control/observe a player
allowtake: HAhadOo
# Whether allow an AI to control a player when the previous controller disconnects
autotoggle: False

# Records the game state and available actions at every step. 
# **Warning**: generates many log files if True. Turned off by default.
record: False
sleep_time_after_turn: 0.0

load_game: ""

trainer:
  epoch: 300
  lr: 1.0e-5
