version: "3"
services:

  # stable version
  freeciv-web:
    image: freeciv/freeciv-web:1.4
    container_name: freeciv-web
    volumes:
      - "data:/var/lib/tomcat10/webapps/data"
    ports:
      - "8080:80"
      - "4002:4002"
      - "6000-6009:6000-6009"
      - "7000-7009:7000-7009"
      - "8888:8080"
    user: docker

  # test version compared with v1.4
  # 1. support build_city ai-assistant;
  # 2. update diplomacy minigame difficulty;
  freeciv-web-test:
    image: freeciv/freeciv-web:1.4.3
    container_name: freeciv-web-test
    environment: 
      host: civrealm-service.mybigai.ac.cn
    ports:
      - "8580:80"
      - "4502:4002"
      - "6500-6509:6000-6009"
      - "7500-7509:7000-7009"
      - "9588:8080"
    user: docker

  # dev version
  freeciv-web-dev:
    image: freeciv/freeciv-web:1.4.3
    container_name: freeciv-web-dev
    ports:
      - "8680:80"
      - "4602:4002"
      - "6600-6609:6000-6009"
      - "7600-7609:7000-7009"
      - "9688:8080"
    user: docker

volumes:
  data:

