version: "3"
services:
  freeciv-web-updates:
    image: freeciv/freeciv-web:1.4
    build: .
    container_name: freeciv-web-updates
    command: ["sleep", "infinity"]
    ports:
      - "8280:80"
      - "4202:4002"
      - "6200-6209:6000-6009"
      - "7200-7209:7000-7009"
      - "9088:8080"
    user: docker

