version: "3"
services:
  freeciv-web-updates:
    image: freeciv/freeciv-web-updates
    build: .
    container_name: freeciv-web-updates
    command: ["sleep", "infinity"]
    volumes:
      - "update_data:/var/lib/tomcat10/webapps/data"
    ports:
      - "8180:80"
      - "4102:4002"
      - "6100-6109:6000-6009"
      - "7100-7109:7000-7009"
      - "8988:8080"
    user: docker

volumes:
  update_data:

