version: "3"
services:

  freeciv-web:
    image: freeciv/freeciv-web
    container_name: freeciv-web
    volumes:
      - "data:/var/lib/tomcat10/webapps/data"
    ports:
      - "8080:80"
      - "4002:4002"
      - "6000-6009:6000-6009"
      - "7000-7009:7000-7009"
      - "8888:8080"
    user: docker
    
  freeciv-web-ai:
    image: freeciv/freeciv-web:1.4.1
    container_name: freeciv-web-ai
    ports:
      - "8580:80"
      - "4502:4002"
      - "6500-6509:6000-6009"
      - "7500-7509:7000-7009"
      - "9588:8080"
    user: docker

volumes:
  data:

