[project]
name = "freeciv-gym"
version = "0.1"
description = "Freeciv Gym is a reinforcement learning environment for the open-source strategy game Freeciv-web."
authors = [
    {name = "Chris1869", email = "chris1869@github.com"},
    {name = "Siyuan Qi", email = "syqi@bigai.ai"},
    {name = "Shuo Chen", email = "chenshuo@bigai.ai"},
    {name = "Xiangyu Kong", email = "kongxiangyu@bigai.ai"},
    {name = "Junqi Wang", email = "wangjunqi@bigai.ai"},
    {name = "Yifan Zhong", email = "zhongyifan@bigai.ai"},
    {name = "Zhaowei Zhang", email = "zhangzhaowei@bigai.ai"},
    {name = "Yexin Li", email = "liyexin@bigai.ai"},
]
readme = "README.md"
license = {text = "GLP3.0"}
dependencies = [
    "pyyaml",
    "overrides",
    "wheel",
    "docker",
    "urllib3", 
    "BitVector", 
    "numpy", 
    "tornado==6.3.2", 
    "gymnasium", 
    "selenium", 
    "websocket-client",
    "pytest",
    "pytest-xdist",
    "filelock",
]


[project.scripts]
update_freeciv_web_docker = "freeciv_gym.freeciv.build_server:update_docker_image"
test_freeciv_gym = "freeciv_gym.random_game:main"

[tool.pytest.ini_options]
addopts = [
    "--import-mode=importlib",
    "-s", # show print statements in console 
    # "-n 16", # specify the number of processes for parallel test
    # specify which test file to run by setting test file name
    # "tests/city/test_city_change_unit_prod.py",
    # "tests/city/test_city_change_improve_prod.py",
    # "tests/city/test_city_change_specialist.py",
    # "tests/city/test_city_unwork.py",
    # "tests/city/test_city_work.py",
    # "tests/city/test_city_buy_prod.py",
    # "tests/city/test_city_sell_improvement.py",
    # "tests/tech/test_choose_research_tech.py",
    # "tests/tech/test_choose_research_goal.py",
    # "tests/player/test_change_government.py",
    # "tests/player/test_player_increase_tax.py",
    # "tests/player/test_player_decrease_tax.py",
    # "tests/unit/test_cultivate.py",
    # "tests/unit/test_irrigation.py",
    # "tests/unit/test_mine.py",
    # "tests/unit/test_plant.py",
    # "tests/unit/test_pillage.py",
    "tests/unit/test_fortress.py",
    # "tests/unit/test_disband.py",
    # "tests/unit/test_get_action_pro.py",
    # "tests/unit/test_attack.py",
]
