[project]
name = "freeciv-gym"
version = "0.1"
description = "Freeciv Gym is a reinforcement learning environment for the open-source strategy game Freeciv-web."
authors = [
    {name = "Chris1869", email = "chris1869@github.com"},
    {name = "Siyuan Qi", email = "syqi@bigai.ai"},
    {name = "Shuo Chen", email = "chenshuo@bigai.ai"},
    {name = "Xiangyu Kong", email = "kongxiangyu@bigai.ai"},
    {name = "Zhaowei Zhang", email = "zhangzhaowei@bigai.ai"},
    {name = "Yexin Li", email = "liyexin@bigai.ai"},
]
readme = "README.md"
license = {text = "GLP3.0"}
dependencies = [
    "pyyaml",
    "overrides",
    "wheel",
    "docker",
    "urllib3", 
    "BitVector", 
    "numpy", 
    "tornado==6.3.2", 
    "gym==0.10.9", 
    "selenium", 
    "websocket-client",
    "pytest",
    "pytest-asyncio",
    "pytest-timeout",
]


[project.scripts]
build_freeciv_server = "freeciv.build_server:build_docker_img"
test_freeciv_gym = "freeciv_gym.random_game:main"

[tool.pytest.ini_options]
addopts = [
    "--import-mode=importlib",
]