version: "3"
services:

  freeciv-web:
    image: freeciv/freeciv-web:latest
    container_name: freeciv-web
    ports:
      - "8080:80"
      - "4002:4002"
      - "6000-6009:6000-6009"
      - "7000-7009:7000-7009"
      - "8888:8080"
      - "1240:1240"
    user: docker

  fciv-net:
    image: freeciv/fciv-net:latest
    container_name: fciv-net
    ports:
      - "8280:80"
      - "4202:4002"
      - "6200-6209:6000-6009"
      - "7200-7209:7000-7009"
      - "9088:8080"
    user: docker

